# Generated by Django 4.0 on 2023-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0002_alter_roadmap_roadmap_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='roadmap',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
