# Generated by Django 4.0 on 2023-09-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0003_alter_roadmap_options_roadmap_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={},
        ),
    ]
