# Generated by Django 4.0 on 2023-09-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0004_alter_roadmap_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='my_order',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
