# Generated by Django 4.0 on 2023-09-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0005_remove_roadmap_my_order_roadmap_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['my_order']},
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='position',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='roadmapapp.job'),
            preserve_default=False,
        ),
    ]
