# Generated by Django 4.0 on 2023-09-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0006_job_alter_roadmap_options_remove_roadmap_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={},
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='job',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='my_order',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
