# Generated by Django 4.0 on 2023-09-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0007_alter_roadmap_options_remove_roadmap_job_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['my_order']},
        ),
        migrations.RenameField(
            model_name='roadmap',
            old_name='position',
            new_name='my_order',
        ),
    ]
