# Generated by Django 4.2.6 on 2023-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0008_alter_roadmap_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='my_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
