# Generated by Django 4.2.7 on 2023-12-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmapapp', '0009_subtopic_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['my_order']},
        ),
    ]
