# Generated by Django 4.2.7 on 2023-12-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewcount1',
        ),
    ]
