# Generated by Django 4.2.7 on 2023-12-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_answerquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='answer_date',
            field=models.DateTimeField(auto_now_add=True, default='2018-11-20T15:58:44.767594-06:00'),
            preserve_default=False,
        ),
    ]
